# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

# Experiment parameters
site : 'INCT20955'
model:
  trained_path: 'models/pretrained_weights/resnet152_4sites/resnet152_final.pth'
  hyper_parameters:
    search:
      window_size : 3
      sliding_window : 1
    transformation:
      n_fft : 1024
      hop_length : 256
      n_mels : 128
      f_min : 50
      f_max : 4000