name: pam_inferences_env
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - dask=2023.3.2 
  - joblib=1.2.0
  - matplotlib=3.7.1
  - numpy=1.23.5
  - pandas=2.0.0
  - pip=23.0.1
  - PyYAML=6.0
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=11.6
  - pip:
    - scikit-maad==1.3.12
    - librosa
    - scikit-learn==1.2.2
    - azure-storage-blob==12.16.0
    - tensorflow==2.12.0
    - torchsummary==1.5.1
   
    
