name: pam_inferences_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - dask=2023.3.2 
  - joblib=1.2.0
  - matplotlib=3.7.1
  - numpy=1.23.5
  - pandas=2.0.0
  - PyYAML=6.0
  - pip=23.0.1
  - pip:
    - scikit-maad==1.3.12
    - librosa
    - scikit-learn==1.2.2
    - tensorflow==2.12.0
    - torch==2.0.0
    - torchaudio==2.0.1
    - torchsummary==1.5.1
    - torchvision==0.15.1
    
