batch_size: 16
data_root: /mnt/batch/tasks/shared/LS_root/mounts/clusters/gpu-baseline/code/Users/jscanass/anuraset_pruebas/data/datasets/anurasetv3
device: cuda
image_size:
- 224
- 448
learning_rate: 0.01
model_type: resnet152
multilabel: true
num_classes: 42
num_epochs: 10
num_workers: 4
pretrained: true
seed: 32678456782
weight_decay: 0.001
